# This file exists for us to configure the various tools we execute through config files.
# Some tools (like flake8-black) can only be configured through a config.
# Other tools, we leverage the config since it allows us to comment on the values.

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
combine_as_imports = true
force_single_line = true
