on:
  pull_request_target:
    paths-ignore:
      - "docs/Coding-Conventions.md"
    types:
      - opened
      - reopened

jobs:
  comment_on_pr:
    runs-on: ubuntu-latest
    name: PR comment
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          message: |
            Thank you for contributing! :wave:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
