on:
  pull_request_target:
    paths-ignore:
      - "docs/Coding-Conventions.md"
    types:
      - opened
      - reopened

jobs:
  comment_on_pr:
    runs-on: ubuntu-latest
    name: PR comment
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@8a3fad13c20088e9eb0805666b9fe49509d2fec8 # v1.6.0
        with:
          message: |
            Thank you for contributing! :wave:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
